source('R/BAmodule.R')
source('R/diagnostics.R')
source('R/exponent.R')
source('R/fitness_table.R')
source('R/hd_coef.R')
source('R/hparam_coef.R')
source('R/Nmodule.R')
source('R/remaining_calc_A.R')
source('R/remaining_calc_B.R')
source('R/simulator.R')
source('R/stand_randomizer.R')
source('R/parametric_height.R')
source('R/stand_parameters.R')

hd_coef <- load(file = 'data/hd_coef.rda')
hparam_coef <- load(file = 'data/hparam_coef.rda')
