source('BAmodule.R')
source('diagnostics.R')
source('exponent.R')
source('fitness_table.R')
source('hd_coef.R')
source('hparam_coef.R')
source('Nmodule.R')
source('remaining_calc_A.R')
source('remaining_calc_B.R')
source('simulator.R')
source('stand_randomizer.R')
source('parametric_height.R')
source('stand_parameters.R')

hd_coef <- load(file = 'data/hd_coef.rda')
hparam_coef <- load(file = 'data/hparam_coef.rda')
